# Generated by Django 2.2.4 on 2019-10-28 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Page', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_label', models.CharField(max_length=45)),
                ('creator_fbid', models.CharField(blank=True, max_length=45)),
                ('publish_to', models.ManyToManyField(blank=True, to='Page.Page')),
            ],
        ),
    ]
