# Generated by Django 2.2.4 on 2019-10-28 09:24

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_label', models.CharField(max_length=45)),
                ('action_type', models.CharField(choices=[('Reply', 'Reply'), ('Input', 'Input'), ('Publish', 'Publish')], max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Button',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('button_label', models.CharField(max_length=45)),
                ('button_text', models.CharField(max_length=45)),
                ('action', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Chatbot.Action')),
            ],
        ),
        migrations.CreateModel(
            name='Input',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_label', models.CharField(max_length=45)),
                ('input_placeholder', models.TextField()),
                ('input_type', models.CharField(choices=[('Text', 'Text'), ('Image', 'Image'), ('URL', 'URL')], max_length=45)),
                ('input_action', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Chatbot.Action')),
            ],
        ),
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.TextField()),
                ('user_fbid', models.CharField(max_length=45)),
                ('input_ref', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Chatbot.Input')),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_label', models.CharField(max_length=45)),
                ('message_text', models.TextField()),
                ('buttons', models.ManyToManyField(blank=True, to='Chatbot.Button')),
            ],
        ),
        migrations.AddField(
            model_name='action',
            name='inputs',
            field=models.ManyToManyField(blank=True, to='Chatbot.Input'),
        ),
        migrations.AddField(
            model_name='action',
            name='message',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Chatbot.Message'),
        ),
    ]
