# Generated by Django 2.2.4 on 2019-10-28 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Chatbot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='action',
            name='confirmation',
            field=models.BooleanField(default=False),
        ),
    ]
