# Generated by Django 2.2.4 on 2019-10-31 22:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Chatbot', '0002_action_confirmation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Command',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('command_text', models.CharField(max_length=45)),
                ('command_action', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Chatbot.Action')),
            ],
        ),
    ]
