# Generated by Django 2.2.4 on 2019-11-02 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Chatbot', '0003_command'),
    ]

    operations = [
        migrations.RenameField(
            model_name='action',
            old_name='confirmation',
            new_name='notifation',
        ),
    ]
