# Generated by Django 2.2.4 on 2019-11-02 22:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Chatbot', '0004_auto_20191102_1017'),
    ]

    operations = [
        migrations.RenameField(
            model_name='action',
            old_name='notifation',
            new_name='notification',
        ),
    ]
