# Generated by Django 2.2.4 on 2019-11-04 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Chatbot', '0005_auto_20191102_2245'),
    ]

    operations = [
        migrations.AddField(
            model_name='action',
            name='advertise',
            field=models.BooleanField(default=False),
        ),
    ]
