# Generated by Django 2.2.4 on 2019-11-07 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Chatbot', '0006_action_advertise'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='default',
            field=models.BooleanField(default=False),
        ),
    ]
