# Generated by Django 2.2.4 on 2019-11-08 21:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Chatbot', '0008_message_payment_succeeded'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='message',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Chatbot.Message'),
        ),
        migrations.AlterField(
            model_name='button',
            name='action',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Chatbot.Action'),
        ),
        migrations.AlterField(
            model_name='command',
            name='command_action',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Chatbot.Action'),
        ),
        migrations.AlterField(
            model_name='input',
            name='input_action',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Chatbot.Action'),
        ),
    ]
