# Generated by Django 2.2.4 on 2019-10-28 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('page_fbid', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('page_token', models.CharField(max_length=200)),
                ('page_name', models.CharField(max_length=150)),
                ('page_location', models.CharField(blank=True, max_length=100)),
                ('page_fan_count', models.IntegerField()),
                ('BOT_ENABLED', models.BooleanField(default=False)),
            ],
        ),
    ]
