# Generated by Django 2.2.4 on 2019-10-31 12:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Page', '0002_adminstrator'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adminstrator',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='adminstrator',
            name='last_name',
        ),
        migrations.AddField(
            model_name='adminstrator',
            name='page',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Page.Page'),
            preserve_default=False,
        ),
    ]
