# Generated by Django 2.2.4 on 2019-11-01 21:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Page', '0004_page_subscription_chanllenge'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='page',
            name='subscription_chanllenge',
        ),
    ]
