# Generated by Django 2.2.4 on 2019-11-01 21:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Page', '0005_remove_page_subscription_chanllenge'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('challenge', models.CharField(max_length=45)),
                ('receiver', models.CharField(blank=True, max_length=45)),
                ('notifier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Page.Page')),
            ],
        ),
        migrations.DeleteModel(
            name='Adminstrator',
        ),
    ]
